#ifndef __RELAY_H
#define __RELAY_H

#include "stm32f1xx_hal.h"

#define RELAY_RCC_CLK_ENABLE()          __HAL_RCC_GPIOA_CLK_ENABLE()

#define RELAY1_GPIO          GPIOA
#define RELAY1_GPIO_PIN          GPIO_PIN_4

#define RELAY2_GPIO          GPIOA
#define RELAY2_GPIO_PIN          GPIO_PIN_5

#define RELAY3_GPIO          GPIOA
#define RELAY3_GPIO_PIN          GPIO_PIN_6

#define RELAY4_GPIO          GPIOA
#define RELAY4_GPIO_PIN          GPIO_PIN_7

#define RELAY5_GPIO          GPIOA
#define RELAY5_GPIO_PIN          GPIO_PIN_8

#define RELAY1_ON          HAL_GPIO_WritePin(RELAY1_GPIO, RELAY1_GPIO_PIN, GPIO_PIN_RESET)
#define RELAY1_OFF          HAL_GPIO_WritePin(RELAY1_GPIO, RELAY1_GPIO_PIN, GPIO_PIN_SET)
#define RELAY1_TOGGLE          HAL_GPIO_WritePin(RELAY1_GPIO, RELAY1_GPIO_PIN)

#define RELAY2_ON          HAL_GPIO_WritePin(RELAY2_GPIO, RELAY2_GPIO_PIN, GPIO_PIN_RESET)
#define RELAY2_OFF          HAL_GPIO_WritePin(RELAY2_GPIO, RELAY2_GPIO_PIN, GPIO_PIN_SET)
#define RELAY2_TOGGLE          HAL_GPIO_WritePin(RELAY2_GPIO, RELAY2_GPIO_PIN)

#define RELAY3_ON          HAL_GPIO_WritePin(RELAY3_GPIO, RELAY3_GPIO_PIN, GPIO_PIN_RESET)
#define RELAY3_OFF          HAL_GPIO_WritePin(RELAY3_GPIO, RELAY3_GPIO_PIN, GPIO_PIN_SET)
#define RELAY3_TOGGLE          HAL_GPIO_WritePin(RELAY3_GPIO, RELAY3_GPIO_PIN)

#define RELAY4_ON          HAL_GPIO_WritePin(RELAY4_GPIO, RELAY4_GPIO_PIN, GPIO_PIN_RESET)
#define RELAY4_OFF          HAL_GPIO_WritePin(RELAY4_GPIO, RELAY4_GPIO_PIN, GPIO_PIN_SET)
#define RELAY4_TOGGLE          HAL_GPIO_WritePin(RELAY4_GPIO, RELAY4_GPIO_PIN)

#define RELAY5_ON          HAL_GPIO_WritePin(RELAY5_GPIO, RELAY5_GPIO_PIN, GPIO_PIN_RESET)
#define RELAY5_OFF          HAL_GPIO_WritePin(RELAY5_GPIO, RELAY5_GPIO_PIN, GPIO_PIN_SET)
#define RELAY5_TOGGLE          HAL_GPIO_WritePin(RELAY5_GPIO, RELAY5_GPIO_PIN)

void RELAY_Init();

#endif